/*++

Copyright (C) 2024 Institute for Machine Tools and Industrial Management
TUM School of Engineering and Design
Technical University of Munich

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
	* Redistributions of source code must retain the above copyright
	  notice, this list of conditions and the following disclaimer.
	* Redistributions in binary form must reproduce the above copyright
	  notice, this list of conditions and the following disclaimer in the
	  documentation and/or other materials provided with the distribution.
	* Neither the name of the Technical University of Munich nor the
	  names of its contributors may be used to endorse or promote products
	  derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL TECHNICAL UNIVERSITY OF MUNICH BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#ifndef __CUSTOMCONSTANTS
#define __CUSTOMCONSTANTS

#include "Framework/Application.hpp"
#include "CustomConstants.hpp"

#define JOURNALGROUP_MAIN 0x100
#define JOURNALGROUP_MODULE_PLC 0x101
#define JOURNALGROUP_MODULE_GPIO1 0x102
#define JOURNALGROUP_MODULE_GPIO2 0x103
#define JOURNALGROUP_MODULE_GPIO3 0x104
#define JOURNALGROUP_MODULE_GPIO4 0x105
#define JOURNALGROUP_MODULE_GPIO5 0x106
#define JOURNALGROUP_MODULE_GPIO6 0x107
#define JOURNALGROUP_MODULE_GPIO7 0x108
#define JOURNALGROUP_MODULE_GPIO8 0x109
#define JOURNALGROUP_MODULE_GPIO9 0x110
#define JOURNALGROUP_MODULE_GPIO10 0x111
#define JOURNALGROUP_MODULE_GPIO11 0x112
#define JOURNALGROUP_MODULE_GPIO12 0x113
#define JOURNALGROUP_MODULE_GPIO13 0x114
#define JOURNALGROUP_MODULE_GPIO14 0x115
#define JOURNALGROUP_MODULE_GPIO15 0x116
#define JOURNALGROUP_MODULE_GPIO16 0x117
#define JOURNALGROUP_MODULE_GPIO17 0x118
#define JOURNALGROUP_MODULE_GPIO18 0x119
#define JOURNALGROUP_MODULE_GPIO19 0x120
#define JOURNALGROUP_MODULE_GPIO20 0x121
#define JOURNALGROUP_MODULE_GPIO21 0x122
#define JOURNALGROUP_MODULE_ENCODER 0x123
#define JOURNALGROUP_MODULE_BUSTRANSMITTER 0x124
#define JOURNALGROUP_MODULE_BUILDPLATFORMAXIS 0x125
#define JOURNALGROUP_MODULE_POWDERRESERVOIRAXIS 0x126
#define JOURNALGROUP_MODULE_RECOATERAXISPOWDERBELT 0x127
#define JOURNALGROUP_MODULE_RECOATERAXISLINEAR 0x128
#define JOURNALGROUP_MODULE_SAFEIO1 0x129
#define JOURNALGROUP_MODULE_SAFEIO2 0x130
#define JOURNALGROUP_MODULE_SAFEIO3 0x140



#define JOURNALGROUP_DOOR 0x200

#define JOURNALGROUP_HEATER 0x300

#define JOURNALGROUP_BUILD_PLATFORM_AXIS 0x400
#define JOURNALGROUP_POWDER_RESERVOIR_AXIS 0x500
#define JOURNALGROUP_RECOATER_AXES 0x600
#define JOURNALGROUP_O2SENSOR 0x700
#define JOURNALGROUP_OxygenControl 0x710
#define JOURNALGROUP_GAS_CIRCULATION 0x800
#define JOURNALGROUP_VACUUMSYSTEM 0x900

#define JOURNALVARIABLE_TESTCOUNTER 0x01
#define JOURNALVARIABLE_BLINK 0x02

#define JOURNALVARIABLE_HEATER_DERIVATIVETIMEINSECONDS 0x311
#define JOURNALVARIABLE_HEATER_INTEGRATIONTIMEINSECONDS 0x312
#define JOURNALVARIABLE_HEATER_GAIN 0x313
#define JOURNALVARIABLE_HEATER_FILTERTIMEINSECONDS 0x314
#define JOURNALVARIABLE_HEATER_MINOUTINPERCENT 0x315
#define JOURNALVARIABLE_HEATER_MAXOUTINPERCENT 0x316
#define JOURNALVARIABLE_HEATER_SETPOINTINDEGREECELCIUS 0x317
#define JOURNALVARIABLE_HEATER_TUNE_STEPHEIGHTINDEGREECELCIUS 0x318
#define JOURNALVARIABLE_HEATER_TUNE_MAXACTVALUEINPERCENT 0x319
#define JOURNALVARIABLE_HEATER_TUNE_MINACTVALUEINPERCENT 0x320
#define JOURNALVARIABLE_HEATER_TUNE_SETTLINGTIMEINSECONDS 0x321
#define JOURNALVARIABLE_HEATER_TUNE_MAXTUNINGTIMEINSECONDS 0x322
#define JOURNALVARIABLE_HEATER_PWM_DUTYCYCLE 0x323
#define JOURNALVARIABLE_HEATER_PWM_PERIOD 0x324
#define JOURNALVARIABLE_HEATER_PWM_MAXFREQUENCY 0x325
#define JOURNALVARIABLE_HEATER_PWM_MODE 0x326
#define JOURNALVARIABLE_HEATER_PID_ISINIT 0x327
#define JOURNALVARIABLE_HEATER_TUNE_ISINIT 0x328
#define JOURNALVARIABLE_HEATER_PWM_ISINIT 0x329
#define JOURNALVARIABLE_HEATER_CONTROLLER_ENABLED 0x330
#define JOURNALVARIABLE_HEATER_SETPOINT_ISINIT 0x331

#define JOURNALVARIABLE_BUILDPLATFORMMOVEMENTABSOLUTERELATIVE 0x411
#define JOURNALVARIABLE_BUILDPLATFORMMOVEMENTPOSITION 0x412
#define JOURNALVARIABLE_BUILDPLATFORMMOVEMENTSPEED 0x413
#define JOURNALVARIABLE_BUILDPLATFORMMOVEMENTACCELERATION 0x414
#define JOURNALVARIABLE_REFERENCEBUILDPLATFORM 0x415

#define JOURNALVARIABLE_POWDERRESERVOIRMOVEMENTABSOLUTERELATIVE 0x521
#define JOURNALVARIABLE_POWDERRESERVOIRMOVEMENTPOSITION 0x522
#define JOURNALVARIABLE_POWDERRESERVOIRMOVEMENTSPEED 0x523
#define JOURNALVARIABLE_POWDERRESERVOIRMOVEMENTACCELERATION 0x524
#define JOURNALVARIABLE_REFERENCEPOWDERRESERVOIR 0x525

#define JOURNALVARIABLE_RECOATERPOWDERBELTMOVEMENTABSOLUTERELATIVE 0x631
#define JOURNALVARIABLE_RECOATERPOWDERBELTMOVEMENTPOSITION 0x632
#define JOURNALVARIABLE_RECOATERPOWDERBELTMOVEMENTSPEED 0x633
#define JOURNALVARIABLE_RECOATERPOWDERBELTMOVEMENTACCELERATION 0x634
#define JOURNALVARIABLE_REFERENCERECOATERPOWDERBELT 0x635
#define JOURNALVARIABLE_INITRECOATERPOWDERBELT 0x636

#define JOURNALVARIABLE_RECOATERLINEARMOVEMENTABSOLUTERELATIVE 0x641
#define JOURNALVARIABLE_RECOATERLINEARMOVEMENTPOSITION 0x642
#define JOURNALVARIABLE_RECOATERLINEARMOVEMENTSPEED 0x643
#define JOURNALVARIABLE_RECOATERLINEARMOVEMENTACCELERATION 0x644
#define JOURNALVARIABLE_REFERENCERECOATERLINEAR 0x645
#define JOURNALVARIABLE_INITRECOATERLINEAR 0x646


#define JOURNALVARIABLE_O2INPPM_CHAMBER 0x701
#define JOURNALVARIABLE_O2INPPM_FILTER 0x702
#define JOURNALVARIABLE_OXYGENCONTROL_DERIVATIVETIMEINSECONDS 0x711
#define JOURNALVARIABLE_OXYGENCONTROL_INTEGRATIONTIMEINSECONDS 0x712
#define JOURNALVARIABLE_OXYGENCONTROL_GAIN 0x713
#define JOURNALVARIABLE_OXYGENCONTROL_FILTERTIMEINSECONDS 0x714
#define JOURNALVARIABLE_OXYGENCONTROL_MINOUTINPERCENT 0x715
#define JOURNALVARIABLE_OXYGENCONTROL_MAXOUTINPERCENT 0x716
#define JOURNALVARIABLE_OXYGENCONTROL_SETPOINTINPPM 0x717
#define JOURNALVARIABLE_OXYGENCONTROL_TUNE_STEPHEIGHTINPERCENT 0x718
#define JOURNALVARIABLE_OXYGENCONTROL_TUNE_MAXACTVALUEINPERCENT 0x719
#define JOURNALVARIABLE_OXYGENCONTROL_TUNE_MINACTVALUEINPERCENT 0x720
#define JOURNALVARIABLE_OXYGENCONTROL_TUNE_SETTLINGTIMEINSECONDS 0x721
#define JOURNALVARIABLE_OXYGENCONTROL_TUNE_MAXTUNINGTIMEINSECONDS 0x722
#define JOURNALVARIABLE_OXYGENCONTROL_PWM_DUTYCYCLE 0x723
#define JOURNALVARIABLE_OXYGENCONTROL_PWM_PERIOD 0x724
#define JOURNALVARIABLE_OXYGENCONTROL_PWM_MAXFREQUENCY 0x725
#define JOURNALVARIABLE_OXYGENCONTROL_PWM_MODE 0x726
#define JOURNALVARIABLE_OXYGENCONTROL_PID_ISINIT 0x727
#define JOURNALVARIABLE_OXYGENCONTROL_PWM_ISINIT 0x728
#define JOURNALVARIABLE_OXYGENCONTROL_TUNE_ISINIT 0x729
#define JOURNALVARIABLE_O2_THRESHOLD_DIFFERENC_ECHAMBER_FILTER_IN_PPM 0x730
#define JOURNALVARIABLE_OXYGENCONTROL_CONTROLLER_ENABLED 0x731
#define JOURNALVARIABLE_OXYGENCONTROL_SETPOINT_ISINIT 0x732

#define JOURNALVARIABLE_PUMPSETPOINTINPERCENT 0x801
#define JOURNALVARIABLE_O2_THRESHOLD_CIRCULATION_ON_IN_PPM 0x802
#define JOURNALVARIABLE_O2_THRESHOLD_CIRCULATION_OFF_IN_PPM 0x803

#define JOURNALVARIABLE_PRESSURE_THRESHOLD_VACUUM_OFF_IN_MBAR 0x901
#define JOURNALVARIABLE_PRESSURE_IN_MBAR 0x902

#define JOURNALVARIABLE_RECOATERMOVEMENTSTARTPOSITION 0x51
#define JOURNALVARIABLE_RECOATERMOVEMENTTARGETPOSITION 0x52
#define JOURNALVARIABLE_RECOATERMOVEMENTLINEARAXISSPEED 0x53
#define JOURNALVARIABLE_RECOATERMOVEMENTPOWDERAXISSPEED 0x54
#define JOURNALVARIABLE_RECOATERMOVEMENTLINEARAXISACCELERATION 0x55
#define JOURNALVARIABLE_RECOATERMOVEMENTPOWDERAXISACCELERATION 0x56

#define AXISMOVEMENT_MINAXISID 1
#define AXISMOVEMENT_MAXAXISID 4

#define AXISMOVEMENT_ABSOLUTE 1
#define AXISMOVEMENT_RELATIVE 2

#define AXISID_BUILDPLATFORM 1
#define AXISID_POWDERRESERVOIR 2
#define AXISID_RECOATERPOWDERBELT 3
#define AXISID_RECOATELINEAR 4

#define CONTROLLERID_BUIDLPLATETEMPCONTROL 1
#define CONTROLLERID_OXYGENCONTROL 2

#define O2SENSORFILTER_RANGE_LOWER_INPERCENT 0
#define O2SENSORFILTER_RANGE_UPPER_INPERCENT 25
#define O2SENSORCHAMBER_RANGE_COARSE_LOWER_INPERCENT 0
#define O2SENSORCHAMBER_RANGE_COARSE_UPPER_INPERCENT 25
#define O2SENSORCHAMBER_RANGE_FINE_LOWER_INPPM 0
#define O2SENSORCHAMBER_RANGE_FINE_UPPER_INPPM 1000
#define FACTOR_PERCENT_TO_PPM 10000


#endif //__CUSTOMCONSTANTS
