# Site settings
title: reAM250
email: david.wenzler@tum.de
description: >- # this means to ignore newlines until "baseurl:"
  An open-source research platform for process monitoring and control in powder bed fusion of metals using a laser beam
baseurl: "/reAM250/" # the subpath of your site, e.g. /blog
url: "https://davidwenzler.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: jekyll-theme-cayman
  
plugins:
  - jekyll-seo-tag # Helps with search engine optimization 
  - jekyll-feed # Generates an RSS feed

# Custom navigation links
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /docs/getting-started/
  - title: Documentation
    url: /docs/
  - title: CAD Files
    url: /cad/
  - title: Publications
    url: /publ/
 
# Other configurations
show_downloads: true # Show download buttons (can be used for your CAD data)
show_explore_button: true # Show "Explore the project" button on homepage

# Exclude from processing.
exclude:
  - README.md
  - LICENSE
  - /docs/CAD/ # excluding large CAD files
  
# Build settings
markdown_ext: markdown, md
