# Site settings
title: reAM250
description: "An open-source research platform for process monitoring and control in powder bed fusion of metals using a laser beam"
baseurl: ""
url: "https://davidwenzler.github.io/reAM250/" # Your GitHub Pages URL
github_username: DavidWenzler # Your GitHub username

# Jekyll settings
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

# Permalinks for clean URLs
permalink: /:title/

# Optional plugins (e.g., for SEO)
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude specific files or directories from being processed by Jekyll
exclude:
  - README.md
  - LICENSE
  - /docs/CAD/ # excluding large CAD files

# Build settings
markdown_ext: markdown,md
